window.PLAN_DATA = {
  meta: {
    title: "ML Engineer Journey",
    subtitle: "Frontend → AI/ML Engineer + Google Pro ML Engineer Cert",
    startDate: "2026-05-20",
    totalWeeks: 30,
    totalHours: 1400,
    dailyHours: 4.5,
  },

  phases: [
    {
      id: "phase1",
      title: "Phase 1 — Foundation",
      subtitle: "Python + Toán nền tảng",
      weekRange: "Tuần 1-8",
      hours: 240,
      color: "#6366f1",
      weeks: [
        {
          id: "p1w1-2",
          title: "Tuần 1-2: Python (tận dụng background TS)",
          materials: [
            { label: "Python Crash Course 2nd ed. — Part I (Ch 1-11) [đã sở hữu]", url: "https://nostarch.com/pythoncrashcourse2e" },
            { label: "Python for Everybody — Coursera (free audit, video supplement)", url: "https://www.coursera.org/specializations/python" },
            { label: "LeetCode Easy (30 bài để quen syntax)", url: "https://leetcode.com/" },
          ],
          tasks: [
            { id: "p1w1-t1", label: "Setup Python env (pyenv + venv + VSCode Python extension) + đọc PCC Ch 1" },
            { id: "p1w1-t2", label: "PCC Ch 2-8: variables, lists, dicts, if, loops, input, functions (speed-through 2-3 ngày, có nền TS)" },
            { id: "p1w1-t3", label: "PCC Ch 9-10: classes/OOP (chú ý __init__, __repr__, magic methods khác TS) + files & exceptions" },
            { id: "p1w1-t4", label: "PCC Ch 11: testing với pytest — apply cho deliverable CLI tool" },
            { id: "p1w1-t5", label: "30 LeetCode Easy bằng Python (parallel với reading)" },
          ],
          deliverable: "1 CLI tool nhỏ bằng Python (vd: scraper lấy giá sản phẩm + lưu CSV)",
        },
        {
          id: "p1w3-4",
          title: "Tuần 3-4: NumPy + Pandas + Visualization",
          materials: [
            { label: "Kaggle Learn: Python, Pandas, Data Visualization", url: "https://www.kaggle.com/learn" },
            { label: "Python Data Science Handbook (VanderPlas, free)", url: "https://jakevdp.github.io/PythonDataScienceHandbook/" },
            { label: "Python Crash Course 2nd ed. — Ch 15-17 (matplotlib, Plotly, CSV/JSON, APIs)", url: "https://nostarch.com/pythoncrashcourse2e" },
          ],
          tasks: [
            { id: "p1w3-t1", label: "Kaggle: Python micro-course" },
            { id: "p1w3-t2", label: "Kaggle: Pandas micro-course" },
            { id: "p1w3-t3", label: "Kaggle: Data Visualization micro-course (+ PCC Ch 15 matplotlib làm tài liệu phụ)" },
            { id: "p1w3-t4", label: "PCC Ch 16-17: CSV/JSON loading + gọi REST API (real-world data fetching cho EDA)" },
            { id: "p1w3-t5", label: "Đọc Python Data Science Handbook chapter 2-4 (NumPy + Pandas deep-dive)" },
          ],
          deliverable: "1 Jupyter notebook EDA cho dataset Kaggle (Titanic / e-commerce). Có pandas operations + charts.",
        },
        {
          id: "p1w5-6",
          title: "Tuần 5-6: Toán phần 1 — Linear Algebra + Calculus",
          materials: [
            { label: "3Blue1Brown: Essence of Linear Algebra", url: "https://www.3blue1brown.com/topics/linear-algebra" },
            { label: "Khan Academy Linear Algebra (bài tập)", url: "https://www.khanacademy.org/math/linear-algebra" },
            { label: "3Blue1Brown: Essence of Calculus", url: "https://www.3blue1brown.com/topics/calculus" },
          ],
          tasks: [
            { id: "p1w5-t1", label: "Xem hết 3B1B Linear Algebra (15 videos)" },
            { id: "p1w5-t2", label: "Hiểu vector, matrix, dot product, matmul, eigenvalue (concept)" },
            { id: "p1w5-t3", label: "Xem hết 3B1B Calculus (12 videos)" },
            { id: "p1w5-t4", label: "Hiểu derivative, partial derivative, chain rule, gradient" },
            { id: "p1w5-t5", label: "Khan Academy: làm 50 bài tập linear algebra" },
          ],
          deliverable: "Notebook implement linear regression bằng NumPy thuần (normal equation + gradient descent). KHÔNG dùng sklearn.",
        },
        {
          id: "p1w7-8",
          title: "Tuần 7-8: Toán phần 2 — Statistics & Probability",
          materials: [
            { label: "StatQuest: Statistics Fundamentals playlist", url: "https://www.youtube.com/@statquest" },
            { label: "Khan Academy Statistics & Probability", url: "https://www.khanacademy.org/math/statistics-probability" },
          ],
          tasks: [
            { id: "p1w7-t1", label: "StatQuest Statistics Fundamentals (~6h)" },
            { id: "p1w7-t2", label: "StatQuest Probability playlist (~4h)" },
            { id: "p1w7-t3", label: "Hiểu mean/median/variance, normal/Bernoulli/binomial distribution" },
            { id: "p1w7-t4", label: "Hiểu Bayes theorem, hypothesis testing, p-value" },
            { id: "p1w7-t5", label: "Hiểu confusion matrix, precision/recall/F1, ROC/AUC" },
          ],
          deliverable: "Notebook A/B test analysis trên dataset giả lập (mean, t-test, conclusion).",
        },
      ],
      checkpoint: {
        id: "cp1",
        title: "Checkpoint 1 — Cuối Phase 1 (tuần 8)",
        passRule: "Đạt 4/5 tiêu chí",
        criteria: [
          { id: "cp1-1", label: "Code Python idiomatic không cần nhìn syntax (comprehension, dict, OOP)" },
          { id: "cp1-2", label: "Mở 1 CSV bất kỳ, EDA hoàn chỉnh bằng pandas+matplotlib trong 1h" },
          { id: "cp1-3", label: "Giải thích bằng lời: gradient descent + vì sao đi ngược dấu gradient" },
          { id: "cp1-4", label: "Implement linear regression từ scratch bằng NumPy" },
          { id: "cp1-5", label: "Đọc 1 paper ML cơ bản và hiểu ≥50% công thức" },
        ],
        fallbacks: [
          { failure: "Python yếu (tiêu chí 1,2 không pass)", action: "+2 tuần intensive Python (50 LeetCode, build 1 Flask API)" },
          { failure: "Toán yếu (tiêu chí 3,4 không pass)", action: "+3 tuần học lại 3B1B chậm hơn + Khan Academy. KHÔNG vào Phase 2 sớm" },
          { failure: "Cả hai yếu", action: "Pause cert plan. Đánh giá lại 4-5h/ngày có khả thi không. Có thể lùi cert sang năm sau" },
        ],
      },
    },

    {
      id: "phase2a",
      title: "Phase 2A — Core ML",
      subtitle: "Andrew Ng ML + scikit-learn",
      weekRange: "Tuần 9-14",
      hours: 180,
      color: "#8b5cf6",
      weeks: [
        {
          id: "p2aw9-12",
          title: "Tuần 9-12: Andrew Ng ML Specialization",
          materials: [
            { label: "Andrew Ng — Machine Learning Specialization", url: "https://www.coursera.org/specializations/machine-learning-introduction" },
            { label: "Sách Géron: Hands-On ML with Scikit-Learn & PyTorch — Ch 1, 3, 4, 6, 7 (deep) + Ch 2 (code-along) + Ch 5, 9 (skim)", url: "https://www.oreilly.com/library/view/hands-on-machine-learning/9798341607972/" },
            { label: "Designing ML Systems — Chip Huyen (bản TV, đã sở hữu) — Ch 1, 2, 4", url: "https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/" },
          ],
          tasks: [
            { id: "p2a-t1", label: "Course 1: Supervised ML — Regression & Classification" },
            { id: "p2a-t2", label: "Course 2: Advanced Learning Algorithms (NN cơ bản, Decision Trees)" },
            { id: "p2a-t3", label: "Course 3: Unsupervised Learning, Recommenders, RL" },
            { id: "p2a-t4", label: "Géron: code-along Ch 2 (End-to-End Project) + đọc kỹ Ch 3, 4, 6, 7 (algorithm intuition mà DMLS không cover) + skim Ch 5, 9 (~22h tổng, giảm từ ~40h)" },
            { id: "p2a-t5", label: "Hoàn thành 100% programming assignments" },
            { id: "p2a-t6", label: "Hàng tuần: 1 Kaggle dataset nhỏ (Titanic / House Prices)" },
            { id: "p2a-t7", label: "Đọc DMLS Ch 1-2: set mindset production trước Andrew Ng (viết 1-page summary EN để làm quen terminology gốc)" },
            { id: "p2a-t8", label: "Đọc DMLS Ch 4 (Training Data): áp dụng ngay sampling/labeling/class imbalance vào Kaggle warmup hàng tuần" },
          ],
          deliverable: "Cheat sheet 5 trang tóm tắt tất cả thuật toán đã học.",
        },
        {
          id: "p2aw13-14",
          title: "Tuần 13-14: Project Kaggle end-to-end",
          materials: [
            { label: "Kaggle Telco Customer Churn", url: "https://www.kaggle.com/blastchar/telco-customer-churn" },
            { label: "Olist E-commerce Dataset", url: "https://www.kaggle.com/olistbr/brazilian-ecommerce" },
            { label: "Surprise library cho recommendation", url: "https://surpriselib.com/" },
            { label: "Designing ML Systems — Chip Huyen (bản TV) — Ch 5, 6", url: "https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/" },
          ],
          tasks: [
            { id: "p2a-pr1", label: "Project 1: E-commerce churn HOẶC fraud detection (tabular ML)" },
            { id: "p2a-pr2", label: "Project 2: Recommendation system cơ bản (MovieLens/Olist)" },
            { id: "p2a-pr3", label: "Mỗi project có README rõ ràng (problem, data, approach, metrics)" },
            { id: "p2a-pr4", label: "EDA notebook tách riêng khỏi training notebook" },
            { id: "p2a-pr5", label: "requirements.txt + Makefile reproducible" },
            { id: "p2a-pr6", label: "Discussion limitations (interview thường hỏi)" },
            { id: "p2a-pr7", label: "Push 2 project lên GitHub với pinned repos" },
            { id: "p2a-pr8", label: "Đọc DMLS Ch 5 (Feature Engineering): apply directly vào Project 1 (churn/fraud)" },
            { id: "p2a-pr9", label: "Đọc DMLS Ch 6 (Model Dev & Offline Evaluation): viết phần 'Discussion limitations' của 2 project theo framework chương này" },
          ],
          deliverable: "2 ML project hoàn chỉnh trên GitHub. ≥ Top 50% trên 1 Kaggle competition.",
        },
      ],
      checkpoint: {
        id: "cp2a",
        title: "Checkpoint 2A — Cuối tuần 14",
        passRule: "Đạt 4/5 tiêu chí",
        criteria: [
          { id: "cp2a-1", label: "Giải thích regression vs classification, bias vs variance, L1 vs L2" },
          { id: "cp2a-2", label: "Cho 1 dataset mới, biết tự chọn model phù hợp" },
          { id: "cp2a-3", label: "Train + evaluate + cross-validation 1 model trong 2 giờ" },
          { id: "cp2a-4", label: "2 project trên GitHub với README rõ ràng + reproducible" },
          { id: "cp2a-5", label: "≥ Top 50% trên 1 Kaggle competition" },
        ],
        fallbacks: [
          { failure: "Không hiểu thuật toán (chỉ copy code)", action: "+2 tuần làm lại programming assignments + viết blog explain từng thuật toán" },
          { failure: "Project chưa hoàn chỉnh", action: "+1 tuần focus 1 project, làm tử tế thay vì nhiều mà sơ sài" },
          { failure: "Mất hứng thú", action: "Nghỉ 3-5 ngày. Đọc bài 'ML in production' để recharge motivation" },
        ],
      },
    },

    {
      id: "phase2b",
      title: "Phase 2B — Deep Learning",
      subtitle: "Andrew Ng DL + PyTorch + GenAI",
      weekRange: "Tuần 15-20",
      hours: 180,
      color: "#ec4899",
      weeks: [
        {
          id: "p2bw15-18",
          title: "Tuần 15-18: Andrew Ng DL Specialization + PyTorch",
          materials: [
            { label: "Deep Learning Specialization — Coursera", url: "https://www.coursera.org/specializations/deep-learning" },
            { label: "PyTorch 60-min Blitz", url: "https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html" },
            { label: "Daniel Bourke — PyTorch for Deep Learning (YouTube)", url: "https://www.youtube.com/watch?v=Z_ikDlimN6A" },
            { label: "Sách Géron: Hands-On ML with Scikit-Learn & PyTorch — Ch 10-18 (DL core, PyTorch-first)", url: "https://www.oreilly.com/library/view/hands-on-machine-learning/9798341607972/" },
          ],
          tasks: [
            { id: "p2b-t1", label: "Course 1: Neural Networks and Deep Learning" },
            { id: "p2b-t2", label: "Course 2: Improving Deep NN (regularization, optimization)" },
            { id: "p2b-t3", label: "Course 3: Structuring ML Projects" },
            { id: "p2b-t4", label: "Course 4: CNN" },
            { id: "p2b-t5", label: "Course 5: Sequence Models (RNN, attention) — optional nếu thiếu time" },
            { id: "p2b-t6", label: "PyTorch 60-min Blitz hoàn chỉnh" },
            { id: "p2b-t7", label: "Implement 1 NN từ scratch bằng NumPy (sanity check)" },
            { id: "p2b-t8", label: "Géron Ch 10-11 (ANN + Training Deep NN với PyTorch): đọc song song Andrew Ng Course 1-2, dùng làm reference PyTorch API" },
            { id: "p2b-t9", label: "Géron Ch 12-13 (Custom training loop + DataLoader pipeline): nền tảng code cho 3 project ở tuần 19-20" },
          ],
          deliverable: "1 NN from scratch + master PyTorch basics.",
        },
        {
          id: "p2bw19-20",
          title: "Tuần 19-20: 3 Deep Learning project (CV + NLP + GenAI)",
          materials: [
            { label: "HuggingFace Transformers", url: "https://huggingface.co/docs/transformers" },
            { label: "LangChain documentation", url: "https://python.langchain.com/" },
            { label: "Chroma vector DB", url: "https://www.trychroma.com/" },
          ],
          tasks: [
            { id: "p2b-pr1", label: "Project 3 (CV): Fashion image classifier với transfer learning (ResNet/EfficientNet)" },
            { id: "p2b-pr2", label: "Project 4 (NLP): Sentiment analysis cho review e-commerce (fine-tune BERT/DistilBERT)" },
            { id: "p2b-pr3", label: "Project 5 (GenAI): RAG chatbot cho product catalog (LangChain + OpenAI/Gemini + Chroma)" },
            { id: "p2b-pr4", label: "Mỗi project: README, architecture diagram, metrics, limitations" },
            { id: "p2b-pr5", label: "Viết ≥ 2 blog technical trên Medium/personal site" },
            { id: "p2b-pr6", label: "Update LinkedIn pinned + bắt đầu networking" },
            { id: "p2b-pr7", label: "Géron Ch 14 (CV/CNN) -> apply Project 3; Ch 15-17 (Sequences/NLP/Transformer) -> apply Project 4" },
            { id: "p2b-pr8", label: "Géron Ch 18 (LLM fine-tuning + HuggingFace) -> reference cho Project 5 (RAG): fine-tune patterns, LoRA/QLoRA" },
          ],
          deliverable: "4-5 project hoàn chỉnh trên GitHub. Bắt đầu apply 2-3 job/tuần (kể cả chưa cert).",
        },
      ],
      checkpoint: {
        id: "cp2b",
        title: "Checkpoint 2B — Cuối tuần 20",
        passRule: "Đạt 5/6 tiêu chí",
        criteria: [
          { id: "cp2b-1", label: "Implement 1 NN từ scratch bằng NumPy (forward + backward)" },
          { id: "cp2b-2", label: "Train 1 CNN, đạt accuracy ≥90% trên Fashion-MNIST" },
          { id: "cp2b-3", label: "Fine-tune 1 transformer model cho task của bạn" },
          { id: "cp2b-4", label: "Build được 1 RAG demo chạy được" },
          { id: "cp2b-5", label: "4-5 project hoàn chỉnh trên GitHub" },
          { id: "cp2b-6", label: "Đã viết ≥ 2 blog technical" },
        ],
        fallbacks: [
          { failure: "Overwhelmed bởi DL", action: "Focus 1 framework (PyTorch), drop RNN/Attention tạm. Cert chỉ test concept" },
          { failure: "RAM/GPU không đủ", action: "Dùng Google Colab free (T4 GPU) hoặc Kaggle Notebook (30h GPU/tuần free)" },
          { failure: "Project GenAI quá khó", action: "Skip RAG, làm Transformer fine-tune đơn giản hơn. Quay lại RAG ở Phase 3" },
        ],
      },
    },

    {
      id: "phase3",
      title: "Phase 3 — GCP + MLOps",
      subtitle: "Vertex AI / Gemini Enterprise + Pipeline",
      weekRange: "Tuần 21-26",
      hours: 180,
      color: "#10b981",
      weeks: [
        {
          id: "p3w21-22",
          title: "Tuần 21-22: GCP Fundamentals + Exam Guide mới",
          materials: [
            { label: "Exam Guide mới (June 2026) — PDF", url: "https://services.google.com/fh/files/misc/professional_machine_learning_engineer_exam_guide_english_new.pdf" },
            { label: "ML Engineer Learning Path — Cloud Skills Boost", url: "https://www.cloudskillsboost.google/paths/17" },
            { label: "Innovators Plus subscription ($299/year)", url: "https://www.cloudskillsboost.google/subscriptions" },
            { label: "Designing ML Systems — Chip Huyen (bản TV) — Ch 3 (Data Engineering Fundamentals)", url: "https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/" },
          ],
          tasks: [
            { id: "p3-t1", label: "Đọc kỹ Exam Guide mới (June 2026)" },
            { id: "p3-t2", label: "Đăng ký Innovators Plus (cover exam fee $200 + $500 credits)" },
            { id: "p3-t3", label: "Setup billing alert GCP ở $10" },
            { id: "p3-t4", label: "Google Cloud Big Data and ML Fundamentals" },
            { id: "p3-t5", label: "Launching into Machine Learning" },
            { id: "p3-t6", label: "5-7 hands-on labs Vertex AI cơ bản" },
            { id: "p3-t7", label: "Đọc DMLS Ch 3 (Data Engineering Fundamentals): trước khi vào BigQuery labs (batch vs streaming, data formats, OLTP vs OLAP)" },
          ],
          deliverable: "Notes/cheat sheet về 6 exam domains.",
        },
        {
          id: "p3w23-24",
          title: "Tuần 23-24: BigQuery ML + Vertex AI + Gemini Enterprise",
          materials: [
            { label: "BigQuery ML docs", url: "https://cloud.google.com/bigquery/docs/bqml-introduction" },
            { label: "Vertex AI documentation", url: "https://cloud.google.com/vertex-ai/docs" },
            { label: "Gemini Enterprise Agent Platform", url: "https://cloud.google.com/blog/products/ai-machine-learning/introducing-gemini-enterprise-agent-platform" },
            { label: "Designing ML Systems — Chip Huyen (bản TV) — Ch 7 (Model Deployment & Prediction Service)", url: "https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/" },
          ],
          tasks: [
            { id: "p3-t8", label: "ML Pipelines on Google Cloud" },
            { id: "p3-t9", label: "Train 1 model bằng BigQuery ML (SQL)" },
            { id: "p3-t10", label: "Deploy 1 model lên Vertex AI endpoint" },
            { id: "p3-t11", label: "Build 1 agent bằng Gemini Enterprise Agent Builder" },
            { id: "p3-t12", label: "Hiểu Model Garden + Vertex AI Agent Builder + RAG patterns" },
            { id: "p3-t13", label: "Đọc DMLS Ch 7 (Model Deployment): core trước khi deploy Vertex AI Endpoint (online vs batch prediction, model compression)" },
          ],
          deliverable: "3 mini demo: BQ ML, Vertex AI endpoint, Gemini agent.",
        },
        {
          id: "p3w25-26",
          title: "Tuần 25-26: MLOps + Project Capstone",
          materials: [
            { label: "MLOps with Vertex AI", url: "https://www.cloudskillsboost.google/journeys/118" },
            { label: "Designing ML Systems — Chip Huyen (bản TV) — Ch 8, 9, 10", url: "https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/" },
          ],
          tasks: [
            { id: "p3-cap1", label: "Capstone: chọn 1 project từ Phase 2 deploy full pipeline" },
            { id: "p3-cap2", label: "Data trong BigQuery / Cloud Storage" },
            { id: "p3-cap3", label: "Training pipeline qua Vertex AI Pipelines / Kubeflow" },
            { id: "p3-cap4", label: "Model serve qua Vertex AI Endpoint" },
            { id: "p3-cap5", label: "CI/CD qua Cloud Build trigger trên git push" },
            { id: "p3-cap6", label: "Monitoring qua Vertex AI Model Monitoring" },
            { id: "p3-cap7", label: "Architecture diagram + README + cost analysis" },
            { id: "p3-cap8", label: "Đọc DMLS Ch 8 (Data Distribution Shifts & Monitoring): apply trực tiếp vào task p3-cap6 (Vertex AI Model Monitoring)" },
            { id: "p3-cap9", label: "Đọc DMLS Ch 9 (Continual Learning & Test in Production): hiểu shadow/canary/A-B deployment patterns — hay ra trong exam" },
            { id: "p3-cap10", label: "Đọc DMLS Ch 10 (Infrastructure & Tooling for MLOps): context conceptual cho Vertex AI Pipelines/Kubeflow" },
          ],
          deliverable: "1 production-grade capstone project live trên GCP (đây là project ăn tiền interview).",
        },
      ],
      checkpoint: {
        id: "cp3",
        title: "Checkpoint 3 — Cuối tuần 26",
        passRule: "Đạt 5/6 tiêu chí",
        criteria: [
          { id: "cp3-1", label: "Train + deploy 1 model lên Vertex AI Endpoint trong 1h without docs" },
          { id: "cp3-2", label: "Viết được 1 Vertex AI Pipeline có ≥3 steps" },
          { id: "cp3-3", label: "Giải thích: AutoML vs Custom training vs Pre-trained API" },
          { id: "cp3-4", label: "Build 1 agent bằng Gemini Enterprise Agent Builder / Model Garden" },
          { id: "cp3-5", label: "Capstone live trên GCP" },
          { id: "cp3-6", label: "Đạt ≥70% trên 1 mock exam đầu tiên" },
        ],
        fallbacks: [
          { failure: "GCP credits hết quá nhanh", action: "Quay lại Cloud Skills Boost labs (free credits). Bật Innovators Plus nếu chưa" },
          { failure: "Quá nhiều GCP services chưa biết", action: "80/20: Vertex AI + BQ ML + Cloud Storage + Cloud Functions = 80% exam. Skip Dataproc/Spark trừ khi guide nhấn mạnh" },
          { failure: "Mock exam < 50%", action: "+2 tuần Phase 3, đọc lại docs domain yếu. KHÔNG đi Phase 4" },
          { failure: "Không hiểu MLOps", action: "Học Made With ML (free) — focus production ML, sát thực tế" },
        ],
      },
    },

    {
      id: "phase4",
      title: "Phase 4 — Cert Prep + Thi",
      subtitle: "Sybex + Mock exams + Exam day",
      weekRange: "Tuần 27-30",
      hours: 120,
      color: "#f59e0b",
      weeks: [
        {
          id: "p4w27",
          title: "Tuần 27: Sybex book + Exam guide comparison",
          materials: [
            { label: "Sách Sybex (đã mua)", url: "https://www.wiley.com/en-es/Official+Google+Cloud+Certified+Professional+Machine+Learning+Engineer+Study+Guide-p-9781119981565" },
            { label: "Exam Guide mới (June 2026)", url: "https://services.google.com/fh/files/misc/professional_machine_learning_engineer_exam_guide_english_new.pdf" },
          ],
          tasks: [
            { id: "p4-t1", label: "Đọc Sybex chapter 1-12, skip phần đã thành thạo" },
            { id: "p4-t2", label: "Note phần outdated (Vertex AI cũ vs Gemini Enterprise mới)" },
            { id: "p4-t3", label: "Làm practice questions cuối mỗi chương Sybex" },
            { id: "p4-t4", label: "Viết cheat sheet 10-15 trang theo 6 domains" },
            { id: "p4-t4b", label: "Géron Ch 1 (ML Landscape) flip 30 phút: refresh terminology trước khi vào Sybex (optional)" },
            { id: "p4-t5", label: "Đọc DMLS Ch 11 (Human Side / Responsible AI): bổ sung 1 section 'Responsible AI / Fairness' vào cheat sheet — hay có 2-3 câu trong exam domain 4" },
          ],
          deliverable: "Cheat sheet 10-15 trang.",
        },
        {
          id: "p4w28",
          title: "Tuần 28: Cloud Skills Boost full path + Sample questions",
          materials: [
            { label: "Google Sample Questions (free)", url: "https://cloud.google.com/learn/certification/machine-learning-engineer" },
            { label: "Whizlabs Practice Exams", url: "https://www.whizlabs.com/" },
            { label: "Tutorials Dojo Practice Exams", url: "https://tutorialsdojo.com/" },
          ],
          tasks: [
            { id: "p4-t6", label: "Hoàn thành 100% Cloud Skills Boost ML Engineer Path" },
            { id: "p4-t7", label: "Làm Google sample questions + đọc giải thích" },
            { id: "p4-t8", label: "Mock exam 1 — target ≥70%" },
            { id: "p4-t9", label: "Review từng câu sai, update cheat sheet" },
          ],
          deliverable: "Mock 1 score ≥70%.",
        },
        {
          id: "p4w29",
          title: "Tuần 29: Mock exam intensive",
          materials: [],
          tasks: [
            { id: "p4-t10", label: "Mock exam 2 (2h như thi thật)" },
            { id: "p4-t11", label: "Mock exam 3" },
            { id: "p4-t12", label: "Mock exam 4 — target ≥80%" },
            { id: "p4-t13", label: "Sau mỗi mock: 2-3h review câu sai, viết lý do" },
          ],
          deliverable: "Mock 3-4 score ≥80%.",
        },
        {
          id: "p4w30",
          title: "Tuần 30: Final review + Thi",
          materials: [
            { label: "Đặt lịch thi", url: "https://cp.certmetrics.com/google/en/login" },
          ],
          tasks: [
            { id: "p4-t14", label: "Ngày 1-3: review cheat sheet + Google sample questions" },
            { id: "p4-t15", label: "Ngày 4: mock exam cuối ≥80%" },
            { id: "p4-t16", label: "Ngày 5: đặt lịch thi (online proctored)" },
            { id: "p4-t17", label: "Ngày 6: REST hoàn toàn, không học gì" },
            { id: "p4-t18", label: "Ngày 7: THI" },
          ],
          deliverable: "PASS exam → có cert.",
        },
      ],
      checkpoint: {
        id: "cp4",
        title: "Checkpoint 4 — Exam Day",
        passRule: "PASS exam",
        criteria: [
          { id: "cp4-1", label: "Cert Google Professional Machine Learning Engineer" },
        ],
        fallbacks: [
          { failure: "Trượt cận biên (~65-70%)", action: "Đợi 14 ngày retake. Focus 2 tuần domain yếu nhất. Lần 2 hầu như đậu" },
          { failure: "Trượt sâu (<60%)", action: "Phase 3 chưa solid. Lùi 4-6 tuần, học lại MLOps + Vertex AI sâu hơn" },
          { failure: "Lo lắng / không tự tin", action: "Trì hoãn thi 2-4 tuần. Retake fee $200 + cooldown 14 ngày — đừng vội" },
          { failure: "Đã có job offer", action: "Cert có thể bỏ — goal chính là job đã đạt" },
        ],
      },
    },
  ],

  jobHunt: {
    startWeek: 16,
    targetRoles: [
      { title: "MLOps Engineer / ML Platform Engineer", fit: "Sweetspot cho SE background" },
      { title: "ML Engineer (Applied)", fit: "Production ML, leverage 9y SE" },
      { title: "AI Engineer / GenAI Engineer", fit: "Đang hot, ít competition vì mới" },
      { title: "Software Engineer with ML", fit: "Backup option, easier entry" },
    ],
    avoid: ["Research Scientist", "Senior Data Scientist", "ML Researcher"],
    niche: "ML cho e-commerce — recommendation, search ranking, fraud, pricing, customer churn. Domain knowledge 9 năm là vũ khí.",
    tasks: [
      { id: "jh-1", label: "Update LinkedIn title: 'Software Engineer (9y) | Transitioning to ML Engineer'" },
      { id: "jh-2", label: "Update LinkedIn headline với journey + ngành e-commerce" },
      { id: "jh-3", label: "Update GitHub: pinned 3-5 project chất lượng" },
      { id: "jh-4", label: "Resume version 1: SE-focused (fallback)" },
      { id: "jh-5", label: "Resume version 2: ML-focused (target)" },
      { id: "jh-6", label: "Setup tracker Notion/Trello cho applications" },
      { id: "jh-7", label: "50 LeetCode Easy + 50 Medium (Python)" },
      { id: "jh-8", label: "5-7 STAR story chuẩn bị behavioral" },
      { id: "jh-9", label: "Tham gia GDG Vietnam community" },
      { id: "jh-10", label: "Tham gia AI Saigon / MLOps Vietnam" },
      { id: "jh-11", label: "1 PR/tháng vào open source ML project" },
      { id: "jh-12", label: "2-3 coffee chat/tuần với ML eng" },
      { id: "jh-13", label: "Apply 5-10 jobs/tuần (từ tuần 21)" },
      { id: "jh-14", label: "≥2 phone screen (checkpoint sau 12 tuần apply)" },
      { id: "jh-15", label: "≥1 technical interview" },
      { id: "jh-16", label: "≥1 offer hoặc final round" },
    ],
  },

  costs: {
    options: [
      {
        id: "optimal",
        title: "Tối ưu (recommended)",
        total: 773,
        items: [
          { label: "Coursera Plus annual", price: 399, note: "Cover Andrew Ng ML + DL + DeepLearning.AI khác" },
          { label: "Google Cloud Skills Boost — Innovators Plus", price: 299, note: "$500 GCP credits + voucher exam $200 + $500 sau khi pass" },
          { label: "Sách Hands-On ML (Géron, PyTorch ed., 2025)", price: 55, note: "ISBN 9798341607972, có trên O'Reilly Learning" },
          { label: "Practice exams (Tutorials Dojo / Whizlabs)", price: 20, note: "" },
          { label: "Sách Sybex", price: 0, note: "Đã mua" },
          { label: "Exam fee", price: 0, note: "FREE qua Innovators Plus voucher" },
        ],
      },
      {
        id: "budget",
        title: "Tiết kiệm (budget)",
        total: 280,
        items: [
          { label: "Coursera (audit free)", price: 0, note: "Không có cert Coursera" },
          { label: "Cloud Skills Boost Starter (free) + GCP free $300", price: 0, note: "Cẩn thận resource" },
          { label: "Sách Géron PyTorch ed. (mượn / O'Reilly trial)", price: 0, note: "" },
          { label: "Practice exams (ExamTopics free)", price: 0, note: "Đọc comment vì community-driven" },
          { label: "Optional Coursera cert 1-2 tháng", price: 80, note: "Cho LinkedIn nếu muốn" },
          { label: "Exam fee", price: 200, note: "Không có voucher" },
        ],
      },
      {
        id: "medium",
        title: "Trung bình",
        total: 470,
        items: [
          { label: "Andrew Ng ML + DL (3 tháng x $49)", price: 147, note: "Lấy cert" },
          { label: "Cloud Skills Boost Pro 3 tháng x $29", price: 87, note: "" },
          { label: "Sách Géron (PyTorch ed.)", price: 55, note: "" },
          { label: "Practice exams", price: 20, note: "" },
          { label: "Exam fee", price: 200, note: "" },
        ],
      },
    ],
    warnings: [
      "GCP usage ngoài free credit: tắt resource sau lab. Set billing alert $10",
      "Internet + electricity ~$30/tháng — không tính trong này",
      "Sách 'Designing ML Systems' (Chip Huyen) — đã sở hữu bản tiếng Việt, tích hợp vào Phase 2A & Phase 3; 'Deep Learning' (Goodfellow) free PDF optional",
    ],
  },

  risks: [
    {
      id: "r1",
      title: "Burnout sau 4-6 tháng",
      signs: "Ngủ không yên, học không vào, chán project",
      action: "Nghỉ trọn 1 tuần. Sau đó giảm 3h/ngày 2 tuần. Apply 1-2 job sớm để cảm nhận gần goal.",
    },
    {
      id: "r2",
      title: "Tiền dự trữ hết trước khi có job",
      signs: "Tháng thứ 6 còn ít savings",
      action: "Nhận freelance FE/React part-time 10-20h/tuần. KHÔNG full-time. Hoặc apply 'SE with ML' role sớm.",
    },
    {
      id: "r3",
      title: "Exam guide thay đổi giữa chừng",
      signs: "Vertex AI → Gemini Enterprise Agent Platform (đã xảy ra)",
      action: "Focus khái niệm core (deploy, monitor, pipeline). Theo dõi Google Cloud release notes 15p/tuần.",
    },
    {
      id: "r4",
      title: "Học mà không apply được",
      signs: "Đọc/xem nhiều nhưng code không ra",
      action: "Quy tắc 2/1: 2 tuần course → 1 mini project. Không đạt = ĐỎ ALERT.",
    },
    {
      id: "r5",
      title: "Market AI/ML co lại",
      signs: "Ít job posting, nhiều layoff",
      action: "Plan B: SE with ML role. Plan C: freelance ML cho startup. Plan D: remote cho công ty Mỹ/Sing/Âu.",
    },
  ],

  weeklyRoutine: [
    { day: "T2-T6", morning: "Lý thuyết (video/sách) — 2h", noon: "Code hands-on — 2h", evening: "Review + Anki / notes — 1-2h" },
    { day: "T7", morning: "Project deep work — 2h", noon: "Project deep work — 2h", evening: "Blog / GitHub push — 1h" },
    { day: "CN", morning: "REST (tuyệt đối)", noon: "Rest hoặc đọc nhẹ", evening: "Plan tuần sau" },
  ],

  successCriteria: [
    { id: "sc1", milestone: "Python + EDA solid", week: 8, condition: "EDA + linear regression from scratch" },
    { id: "sc2", milestone: "Andrew Ng ML done", week: 14, condition: "2 Kaggle project trên GitHub" },
    { id: "sc3", milestone: "Andrew Ng DL + GenAI", week: 20, condition: "4-5 project, 1 RAG demo" },
    { id: "sc4", milestone: "GCP + MLOps capstone", week: 26, condition: "1 model deploy full pipeline GCP" },
    { id: "sc5", milestone: "Cert exam", week: 30, condition: "Pass exam" },
    { id: "sc6", milestone: "First phone screen", week: 24, condition: "≥2 phone screen sau 4 tuần apply" },
    { id: "sc7", milestone: "First offer", week: 40, condition: "≥1 offer hoặc final round" },
  ],
};
